# -*- coding: utf-8 -*-
"""05-03-24 Big_Data-Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16eS82QxGUYr7Nz6_ESNX3yMkJaHUrBKX
"""

importimport numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

"""Load Dataset"""

df = pd.read_csv('/content/drive/MyDrive/content/student_info.csv')

df.head()

df.info()

df.describe()

plt.scatter(x =df.study_hours, y = df.student_marks)
plt.xlabel("Students Study Hours")
plt.ylabel("Students Marks")
plt.title("Scatter Plot of Student Study Hours VS Student marks")
plt.show()

df.isnull().sum()

df.mean()

df2 = df.fillna(df.mean())

df2.isnull().sum()

df2.head()

x = df2.drop("student_marks", axis= "columns")
y = df2.drop("study_hours", axis= "columns")
print("shape of x =", x.shape)
print("shape of y =", y.shape)

from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=51)
print("Shape of X_train= ", x_train.shape)
print("Shape of X_test= ", x_test.shape)
print("Shape of y_train= ", y_train.shape)
print("Shape of y_test= ", y_test.shape)

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(x_train,y_train)

lr.coef_

lr.intercept_

m = 3.93
c = 50.44
y = m*4+c
y

lr.predict([[4]])[0][0].round(2)

y_pred = lr.predict(x_test)
y_pred

pd.DataFrame(np.c_[x_test,y_test,y_pred], columns= ["study_hours", "student_marks_original","student_marks_predicted"])

lr.score(x_test, y_test)

plt.scatter(x_train,y_train)

