# -*- coding: utf-8 -*-
"""AI lab work for lab exam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwRUOlRLMTdJWGgzGA8ypLkflRksoftF
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive/')

df=pd.read_csv('/content/drive/MyDrive/Data set/StudentsPerformance.csv')

df.head()

df.tail()

df.info()

df.isnull().sum()

df.describe()

df.shape

x= df.drop('writing score',axis=1)
x

y=df['writing score'].value_counts()
y

import matplotlib.pyplot as plt
plt.figure()
activities=['female','male']
explode=[0.1,0]
values=df['gender'].value_counts()
fig1,ax1=plt.subplots()
plt.pie(values,labels=activities,explode=explode,autopct='%1.1f%%',shadow=True,startangle=-90)
plt.title("Gender chart\n", fontsize=18,fontweight='bold')
plt.show()

