# -*- coding: utf-8 -*-
"""AI lab per.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RfYNfaKvnwJ9hUPgYkmxJ9XI8wAWW1gF
"""

from google.colab import drive
drive.mount('/content/drive/')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/drive/MyDrive/AI lab final/iris (1).csv')

df

df.head(5)

df.tail(5)

df.info()

df.isnull().sum()

data = df.values

X = data[:,0:4]
Y = data[:,4]
print(X)

data = df.values

X = data[:,0:4]
Y = data[:,4]
print(Y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
print(X_train)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
print(y_train)

from sklearn.linear_model import LinearRegression
lrg = LinearRegression()

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(xtrain, ytrain)

gnb.score(xtest,ytest)*100

from sklearn.preprocessing import LabelEncoder
from pandas.core.dtypes.common import is_numeric_dtype
le=LabelEncoder()

for col in x.columns:
    if is_numeric_dtype(x[col]):
        continue
    x[col]=le.fit_transform(x[col])

