# -*- coding: utf-8 -*-
"""AI-lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pL9RfKFu9BMyZ08dAIr_OJqIwyHAJZws
"""

from google.colab import drive
drive.mount('/content/drive/')

import numpy as np
import pandas as pd
import matplotlib as plt

df=pd.read_csv('/content/drive/MyDrive/Data set/StudentsPerformance.csv')

df.head()

df.info()

df.shape

df.dtypes

df.describe

df.isnull().sum()

"""Geder pie chart"""

import matplotlib.pyplot as plt
plt.figure()
labels=['Female','Male']
explode=[0.1,0]
values=df['gender'].value_counts()
fig1,ax1=plt.subplots()
plt.pie(values,labels=labels,explode=explode,autopct='%1.1f%%',shadow=True,startangle=90)
plt.title('Gender Chart\n',fontsize=18,fontweight='bold')
plt.show

