# -*- coding: utf-8 -*-
"""AI lab final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JwZWoULc7zaupDFfh1Xu24OMJc4LvZs
"""

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
import numpy as np

df=pd.read_csv('/content/drive/MyDrive/AI lab final/USA_Housing for linear_regression.csv')

df

df.head()

df.describe()

df.head(5)

df.tail(5)

df.info



df.shape

df.isnull()

df.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC

data = df.values

X = data[:,0:4]
Y = data[:,4]
print(X)

data = df.values

X = data[:,0:4]
Y = data[:,4]
print(Y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
print(X_train)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
print(y_train)