# -*- coding: utf-8 -*-
"""August29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1tY8kX_1nMr0MbKysBrm-9sAQlIwxaR

**Booleans**
"""

print(10 > 9)
print(10 == 9)
print(10 < 9)

print(10 == 5)

a = 200
b = 33

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")

a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
if a > b:
  print("a is greater than b")
else:
  print("a is not greater than b")

print(bool("hello"))
print(bool(15))

bool("abc")
bool(123)
bool(["apple", "cherry", "banana"])

print(bool("abc"))
print(bool(123))
print(bool(["apple", "cherry", "banana"]))

class myclass():
  def __len__(self):
    return 0

myobj = myclass()
print(bool(myobj))

from typing_extensions import Self
class myclass():
  def __len__(self):
    return 0

myobj = myclass()
print(bool(myobj))

