# -*- coding: utf-8 -*-
"""Big Data Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQOF3Ek73naJe3o2UtalBlwtz8HhtX5X
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/content/read.csv')

df.head()

df.isnull().sum()

x = df.iloc[:, :-1].values
y =  df.iloc[:, 3:].values

from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values = np.nan, strategy = 'mean')
x[:, 1:3] = imp.fit_transform(x[:, 1:3])

x

from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
x[:,0]=LE.fit_transform(x[:,0])

x

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

"""X"""

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

y=LE.fit_transform(y)

y

transform = ColumnTransformer([("norm1", OneHotEncoder(), [0])], remainder = 'passthrough')
x = transform.fit_transform(x)
x

from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
x[:, 3:5]=SC.fit_transform(x[:, 3:5])
x