# -*- coding: utf-8 -*-
"""Big Data 20-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FBIh5_cqRNJQr54PUqgz-WwGpihcvFtY
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/content/train.csv')

df.shape

df.head(6)

df.info()

df.isnull().sum()

plt.figure(figsize=(25,25))
sns.heatmap(df.isnull())



df.shape[0]

null_var = df.isnull().sum()/df.shape[0] *100
null_var

drop_colums = null_var[null_var >17].keys()
drop_colums

df2_drop_clm=df.drop(columns=drop_colums)

df2_drop_clm.shape

sns.heatmap(df2_drop_clm.isnull())

df3_drop_rows = df2_drop_clm.dropna()

df3_drop_rows.shape

plt.figure(figsize=(25,25))
sns.heatmap(df3_drop_rows.isnull())

df3_drop_rows.isnull().sum().sum()

df3_drop_rows.select_dtypes(include=['int64','float64']).columns

