# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NoILqtGZcbM-Iyor2ELOf1APuaoMBxXa
"""

def calculator():
    print("Welcome to the Python Calculator!")
    print("Enter 'quit' to end the program.")
    print("Enter 'clear' to clear the input.")

    while True:
        user_input = input("Enter the calculation you would like to perform (e.g. 2 + 2): ")
        if user_input == 'quit':
            break
        elif user_input == 'clear':
            continue
        try:
            result = eval(user_input)
            print("Result: ", result)
        except:
            print("Invalid input, please try again.")

calculator()

