# -*- coding: utf-8 -*-
"""DBML-lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVj1FlmDGVYQmtQRmCcsGEn-OBzDhBnV

1.
"""

import

"""2."""

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df["Notun id"]=lb.fit_transform(df["id"])
df

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df["Notun gender"]=lb.fit_transform(df["gender"])
df

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df["Notun s11"]=lb.fit_transform(df["s11"])
df

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df["Notun s12"]=lb.fit_transform(df["s12"])
df

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df["Notun s16"]=lb.fit_transform(df["s16"])
df

"""3."""

a=0
b

"""4."""

count = 0
sum = 0
for i in range(7):
  value = float(input("input value: "))
  if value > 0:
    count = count +1
    sum = sum + value
    avr = sum / count
neg = 7 - count
print(f"Negative numbers : {neg}")
print(f"The avarage is : {avr:.1f}")

