# -*- coding: utf-8 -*-
"""DBML lab-final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13joaZ5tZWb7vM2M426NtMFO0g3NEcfhv
"""

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('/content/drive/MyDrive/Data set/honolulu.csv')

df

df.head()

x=df['ssc_p']
y=df['hsc_p']
plt.scatter(x,y,c='g')

x=df['ssc_p']
y=df['hsc_p']
x1=df['degree_p']
y1=df['degree_t']
plt.scatter(x,y,c='g')
plt.scatter(x,y,c='cyan')

slices = df['gender'].value_counts
activity = ['ssc_p','ssc_b']

plt.pie('x')

df.isnull()

df.isnull().sum()

x=df['gender']
y=df

df["mba_p"].fillna(df["mba_p"].mean(),inplace = True)
df

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

data = df.values

X = data[:,0:4]
Y = data[:,4]
print(X)

data = df.values

X = data[:,0:4]
Y = data[:,4]
print(Y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
print(X_train)

from sklearn.svm import SVC

model_svc = SVC()
model_svc.fit(X_train, y_train)

