# -*- coding: utf-8 -*-
"""name.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wYxsTKrimx3520LmZDjRcr4flycpIw4
"""

a = 'I am abir hossen. I am from Kushtia, Khulna. I am a sutdent'
if 'Daulotpur' in a:
  print('Yes')
else:
  print('No')

print("Abir \n"*10)