# -*- coding: utf-8 -*-
"""pythonincolab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7lrSKmy4LaEWZhZ1Uo0tzGmIjUNOAQA
"""

print("hello world")

n=int(input("Enter number: "))
k=0
for i in range(2,n//2+1):
    if(n%i==0):
        k=k+1
if(k<=0):
    print("Prime number")
else:
    print("not a prime number")



"""**Python** **practice**"""

x = 5
y = "Abir"
print(x)
print(y)

frouits = ["banana", "apple", "mango"]
x, y, z = frouits
print(x)
print(z)
print(y)

"""**varriable**"""

x = "I am abir hossen"
print(x)

x = "I"
y = "am"
z = "Abir"
a = "hossen"
print(x, y, z, a)

x = "I "
y = "am "
z = "Abir "
a = "hossen"
print(x + y + z + a)

x = "Abir"
def myfunc():
  print("I am " + x)
myfunc()

n=int(input("Enter number: "))
k=0
for i in range(2,n//2+1):
    if(n%i==0):
        k=k+1
if(k<=0):
    print("Prime number")
else:
    print("Not a prime number")

x = "Abir"

#display x:
print(x)

#display the data type of x:
print(type(x))

x = 20.2

#display x:
print(x)

#display the data type of x:
print(type(x))

x = ["apple", "banana", "cherry"]

#display x:
print(x)

#display the data type of x:
print(type(x))

x = range(6)

#display x:
print(x)

#display the data type of x:
print(type(x))

