# -*- coding: utf-8 -*-
"""Raisul.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-bbwmGXBZV30kzrr3Nafs-TXU3n9SQ1S
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Bigdata/Raisul15.csv')

df.head()

x = df.iloc[:, :-1].values
y =  df.iloc[:, 3:].values

from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values = np.nan, strategy = 'mean')
x[:, 1:3] = imp.fit_transform(x[:, 1:3])

x

from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
x[:, 0] = LE.fit_transform(x[:, 0])

x

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

transform = ColumnTransformer([("norm1", OneHotEncoder(), [0])], remainder = 'passthrough')
x = transform.fit_transform(x)
x

y = LE.fit_transform(y)

from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
x[:, 3:5]=SC.fit_transform(x[:, 3:5])
x