# -*- coding: utf-8 -*-
"""September-14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axWnXm_AONhDV8_T25gkuUzosC6nT8PO
"""

print(10 + 5)

print(50 / 10)

"""# **Squre korar jonno**"""

x = 5
y = 3

print(x ** y)

x = 2
y = 2

print(x ** y)

"""#the floor division"""

x = 20
y = 3

print(x // y)

"""# Python Assignment Operators"""

x = 5
x += 2
print(x)

"""# List"""

thislist = ["apple", "banana", "cherry"]
print(thislist)

list = ["abir", "hossen", "brinto"]
print(list)

thislist = ["apple", "banana", "cherry", "apple", "cherry"]

print(thislist)

thislist = ["apple", "banana", "cherry", "apple", "cherry"]

print(len(thislist))

thislist = ["My", "name","is","Abir"]
print(len(thislist))

list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]

print(list1)
print(list2)
print(list3)

list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]

print(list1)
print(len(list2))
print(list3)

list1 = ["abc", 34, True, 40, "male"]

print(list1)

list1 = ["abc", 34, True, 40, "male"]

print(list1)
print(len(list1))

list1 = ["abc", 34, True, 40, "male"]

print(type(list1))

