# -*- coding: utf-8 -*-
"""Sept-17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmiIKCa0wA5OI7j7HWKn-UU9UNXxRXJb
"""

a = float(input("Enter a :"))
b = float(input("Enter b :"))
c = float(input("Enter c :"))
if (c>a>b) :
  middlevalue = a
elif (c>b>a):
  middlevalue = b
else:
  middlevalue = c
print("the middle number is ",middlevalue)

a = float(input("Enter a :"))
b = float(input("Enter b :"))
c = float(input("Enter c :"))
if (a>b)and(a>c) :
  bigvalue = a
elif (a<b) and (c<b) :
  bigvalue = b
else:
  bigvalue = c
print("the largest number is ",bigvalue)

a = float(input("Enter a :"))
b = float(input("Enter b :"))
c = float(input("Enter c :"))
if (b<a>c) :
  bigvalue = a
elif (a<b>c) :
  bigvalue = b
else:
  bigvalue = c
print("the largest number is ",bigvalue)

a = float(input("Enter a number: "))
b = float(input("Enter a number: "))
print(a+b)

a = float(input("Enter a number: "))
b = float(input("Enter a number: "))
c = float(input("Enter a number; "))
if (c>a>b):
  yourvalue = a
elif (c>b>a):
  yourvalue = b
else:
  yourvalue = c
print("Your value is: ",yourvalue)

