# -*- coding: utf-8 -*-
"""SmoteFunction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Oi_DDDiPZ1pn5GSPvcOHh8iOkleqEN2
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from imblearn.over_sampling import SMOTE

df = pd.read_csv('/content/drive/MyDrive/content/creditcard.csv')

df.shape

df.head(6)

import warnings
warnings.filterwarnings('ignore')

df.isnull().sum()

X, y = make_classification(n_classes=3, class_sep=2, weights=[0.1, 0.3, 0.6], n_informative=4, n_redundant=1, flip_y=0, n_features=25, n_clusters_per_class=1, n_samples=1000, random_state=42)

print('Original class distribution:', Counter(y))

print("Class distribution before SMOTE:")
print(pd.Series(y_train).value_counts())

